apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod-1
spec:
  volumes:
    - name: task-pv-storage-1
      persistentVolumeClaim:
        claimName: task-pv-claim-1
  containers:
    - name: task-pv-container-1
      image: sw23/corns
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage-1
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
